# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10


[[main]]
  name = "Research"
  url = "#projects"
  weight = 20

[[main]]
  name = "Morbid Curiosity Scale"
  url = "#mcs"
  weight = 25

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40

[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 50
  
[[main]]
  name = "Press"
  url = "#press"
  weight = 55

[[main]]
  name = "CV"
  url = "files/Scrivner_Curriculum_Vitae.pdf"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70
